[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "troute-network"
version = "0.1.0"
description = "A package for channel network routing analysis plucked from t-route"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "geopandas",
    "pandas",
    "xarray",
    "netcdf4",
    "requests",
    "tqdm",
    "fiona",
    "shapely"
]

[tool.setuptools.packages.find]
where = ["src"]
